name: Linting Workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - '*' 

jobs:
  testing:
    name: Lint Check and Testing

    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Check the code with ktlint
      - name: Run Kotlin Linter
        run: ./gradlew ktlintCheck

